// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oAPsVEPE9NjWT8tDm6c68U
// Component: UykUXnw_yz
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_feed.module.css"; // plasmic-import: oAPsVEPE9NjWT8tDm6c68U/projectcss
import sty from "./PlasmicFeedList.module.css"; // plasmic-import: UykUXnw_yz/css

export type PlasmicFeedList__VariantMembers = {};
export type PlasmicFeedList__VariantsArgs = {};
type VariantPropType = keyof PlasmicFeedList__VariantsArgs;
export const PlasmicFeedList__VariantProps = new Array<VariantPropType>();

export type PlasmicFeedList__ArgsType = {};
type ArgPropType = keyof PlasmicFeedList__ArgsType;
export const PlasmicFeedList__ArgProps = new Array<ArgPropType>();

export type PlasmicFeedList__OverridesType = {
  root?: p.Flex<"section">;
  text?: p.Flex<"div">;
  list1?: p.Flex<"div">;
  list2?: p.Flex<"div">;
  list3?: p.Flex<"div">;
  list4?: p.Flex<"div">;
};

export interface DefaultFeedListProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    await promise;
  });

function PlasmicFeedList__RenderFunc(props: {
  variants: PlasmicFeedList__VariantsArgs;
  args: PlasmicFeedList__ArgsType;
  overrides: PlasmicFeedList__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <p.Stack
      as={"section"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"Feed  List"}
      </div>

      <div
        data-plasmic-name={"list1"}
        data-plasmic-override={overrides.list1}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.list1)}
      >
        {"List 1\n"}
      </div>

      <div
        data-plasmic-name={"list2"}
        data-plasmic-override={overrides.list2}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.list2)}
      >
        {"List 2\n"}
      </div>

      <div
        data-plasmic-name={"list3"}
        data-plasmic-override={overrides.list3}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.list3)}
      >
        {"List 3\n"}
      </div>

      <div
        data-plasmic-name={"list4"}
        data-plasmic-override={overrides.list4}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.list4)}
      >
        {"List 4 \n"}
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "text", "list1", "list2", "list3", "list4"],
  text: ["text"],
  list1: ["list1"],
  list2: ["list2"],
  list3: ["list3"],
  list4: ["list4"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "section";
  text: "div";
  list1: "div";
  list2: "div";
  list3: "div";
  list4: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFeedList__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFeedList__VariantsArgs;
    args?: PlasmicFeedList__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFeedList__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicFeedList__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicFeedList__ArgProps,
          internalVariantPropNames: PlasmicFeedList__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicFeedList__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFeedList";
  } else {
    func.displayName = `PlasmicFeedList.${nodeName}`;
  }
  return func;
}

export const PlasmicFeedList = Object.assign(
  // Top-level PlasmicFeedList renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),
    list1: makeNodeComponent("list1"),
    list2: makeNodeComponent("list2"),
    list3: makeNodeComponent("list3"),
    list4: makeNodeComponent("list4"),

    // Metadata about props expected for PlasmicFeedList
    internalVariantProps: PlasmicFeedList__VariantProps,
    internalArgProps: PlasmicFeedList__ArgProps
  }
);

export default PlasmicFeedList;
/* prettier-ignore-end */
