// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oAPsVEPE9NjWT8tDm6c68U
// Component: 0aRDxPuCXW
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import FeedList from "../../FeedList"; // plasmic-import: UykUXnw_yz/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_feed.module.css"; // plasmic-import: oAPsVEPE9NjWT8tDm6c68U/projectcss
import sty from "./PlasmicFirst.module.css"; // plasmic-import: 0aRDxPuCXW/css

export type PlasmicFirst__VariantMembers = {};
export type PlasmicFirst__VariantsArgs = {};
type VariantPropType = keyof PlasmicFirst__VariantsArgs;
export const PlasmicFirst__VariantProps = new Array<VariantPropType>();

export type PlasmicFirst__ArgsType = {};
type ArgPropType = keyof PlasmicFirst__ArgsType;
export const PlasmicFirst__ArgProps = new Array<ArgPropType>();

export type PlasmicFirst__OverridesType = {
  root?: p.Flex<typeof FeedList>;
};

export interface DefaultFirstProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    await promise;
  });

function PlasmicFirst__RenderFunc(props: {
  variants: PlasmicFirst__VariantsArgs;
  args: PlasmicFirst__ArgsType;
  overrides: PlasmicFirst__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <FeedList
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof FeedList;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFirst__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFirst__VariantsArgs;
    args?: PlasmicFirst__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFirst__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicFirst__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicFirst__ArgProps,
          internalVariantPropNames: PlasmicFirst__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicFirst__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFirst";
  } else {
    func.displayName = `PlasmicFirst.${nodeName}`;
  }
  return func;
}

export const PlasmicFirst = Object.assign(
  // Top-level PlasmicFirst renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicFirst
    internalVariantProps: PlasmicFirst__VariantProps,
    internalArgProps: PlasmicFirst__ArgProps
  }
);

export default PlasmicFirst;
/* prettier-ignore-end */
